/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as ContentsRouteImport } from './routes/contents'
import { Route as NowRouteImport } from './routes/now'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as AudienceSlugRouteImport } from './routes/audience.$slug'
import { Route as BrandsSlugRouteImport } from './routes/brands_.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsRoute = ContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceSlugRoute = AudienceSlugRouteImport.update({
  id: '/audience/$slug',
  path: '/audience/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands_/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/brands': typeof BrandsRoute
  '/contents': typeof ContentsRoute
  '/now': typeof NowRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/writing': typeof WritingRoute
  '/a/$slug': typeof ASlugRoute
  '/audience/$slug': typeof AudienceSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/brands': typeof BrandsRoute
  '/contents': typeof ContentsRoute
  '/now': typeof NowRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/writing': typeof WritingRoute
  '/a/$slug': typeof ASlugRoute
  '/audience/$slug': typeof AudienceSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/brands': typeof BrandsRoute
  '/contents': typeof ContentsRoute
  '/now': typeof NowRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/writing': typeof WritingRoute
  '/a/$slug': typeof ASlugRoute
  '/audience/$slug': typeof AudienceSlugRoute
  '/brands_/$slug': typeof BrandsSlugRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/brands'
    | '/contents'
    | '/now'
    | '/studio'
    | '/work'
    | '/writing'
    | '/a/$slug'
    | '/audience/$slug'
    | '/brands/$slug'
    | '/c/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/brands'
    | '/contents'
    | '/now'
    | '/studio'
    | '/work'
    | '/writing'
    | '/a/$slug'
    | '/audience/$slug'
    | '/brands/$slug'
    | '/c/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/brands'
    | '/contents'
    | '/now'
    | '/studio'
    | '/work'
    | '/writing'
    | '/a/$slug'
    | '/audience/$slug'
    | '/brands_/$slug'
    | '/c/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BrandsRoute: typeof BrandsRoute
  ContentsRoute: typeof ContentsRoute
  NowRoute: typeof NowRoute
  StudioRoute: typeof StudioRoute
  WorkRoute: typeof WorkRoute
  WritingRoute: typeof WritingRoute
  ASlugRoute: typeof ASlugRoute
  AudienceSlugRoute: typeof AudienceSlugRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents': {
      id: '/contents'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audience/$slug': {
      id: '/audience/$slug'
      path: '/audience/$slug'
      fullPath: '/audience/$slug'
      preLoaderRoute: typeof AudienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands_/$slug': {
      id: '/brands_/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BrandsRoute: BrandsRoute,
  ContentsRoute: ContentsRoute,
  NowRoute: NowRoute,
  StudioRoute: StudioRoute,
  WorkRoute: WorkRoute,
  WritingRoute: WritingRoute,
  ASlugRoute: ASlugRoute,
  AudienceSlugRoute: AudienceSlugRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
